import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        error: "var(--color-error)",
        secondary: "var(--color-secondary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "error-container": "var(--color-error-container)",
        surface: "var(--color-surface)",
        tertiary: "var(--color-tertiary)",
        "on-secondary": "var(--color-on-secondary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-error": "var(--color-on-error)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        outline: "var(--color-outline)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-background": "var(--color-on-background)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary": "var(--color-on-primary)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "inverse-surface": "var(--color-inverse-surface)",
        primary: "var(--color-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        background: "var(--color-background)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "secondary-container": "var(--color-secondary-container)",
        ink: "var(--color-ink)",
        "on-ink": "var(--color-on-ink)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "16px",
        "stack-md": "32px",
        base: "8px",
        "margin-mobile": "20px",
        gutter: "24px",
        "stack-lg": "80px",
        "container-max": "1200px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "headline-h1": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-h2": ["Playfair Display", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-h3": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        button: ["Inter", "sans-serif"],
        "headline-h1-mobile": ["Playfair Display", "serif"],
        small: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-h1": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-h2": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "headline-h3": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": [
          "72px",
          { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        button: [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-h1-mobile": [
          "36px",
          { lineHeight: "44px", fontWeight: "600" },
        ],
        small: ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
